USER=jiwonwoo
PATH=/Users/jiwonwoo/.rbenv/shims:/Users/jiwonwoo/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jiwonwoo/.rbenv/shims:/Users/jiwonwoo/.rbenv/bin
LOGNAME=jiwonwoo
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6QMDSZ5BHV/Listeners
HOME=/Users/jiwonwoo
SHELL=/bin/zsh
__CF_USER_TEXT_ENCODING=0x1F5:0x3:0x33
TMPDIR=/var/folders/_r/ly2pm46125s9hbkjhsrzrr_c0000gn/T/
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/jiwonwoo/Desktop/minishell
OLDPWD=/Users/jiwonwoo/Desktop/minishell
RBENV_SHELL=zsh
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.58.2
LANG=ko_KR.UTF-8
COLORTERM=truecolor
VSCODE_GIT_IPC_HANDLE=/var/folders/_r/ly2pm46125s9hbkjhsrzrr_c0000gn/T/vscode-git-66da11c8a5.sock
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
TERM=xterm-256color
_=/Users/jiwonwoo/Desktop/minishell/./minishell
